/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category InitializeNcnVaultTicket
 * @category generated
 */
export const InitializeNcnVaultTicketStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number
}>(
  [['instructionDiscriminator', beet.u8]],
  'InitializeNcnVaultTicketInstructionArgs'
)
/**
 * Accounts required by the _InitializeNcnVaultTicket_ instruction
 *
 * @property [] config
 * @property [_writable_] ncn
 * @property [] vault
 * @property [_writable_] ncnVaultTicket
 * @property [**signer**] admin
 * @property [_writable_, **signer**] payer
 * @category Instructions
 * @category InitializeNcnVaultTicket
 * @category generated
 */
export type InitializeNcnVaultTicketInstructionAccounts = {
  config: web3.PublicKey
  ncn: web3.PublicKey
  vault: web3.PublicKey
  ncnVaultTicket: web3.PublicKey
  admin: web3.PublicKey
  payer: web3.PublicKey
  systemProgram?: web3.PublicKey
}

export const initializeNcnVaultTicketInstructionDiscriminator = 4

/**
 * Creates a _InitializeNcnVaultTicket_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category InitializeNcnVaultTicket
 * @category generated
 */
export function createInitializeNcnVaultTicketInstruction(
  accounts: InitializeNcnVaultTicketInstructionAccounts,
  programId = new web3.PublicKey('RestkWeAVL8fRGgzhfeoqFhsqKRchg6aa1XrcH96z4Q')
) {
  const [data] = InitializeNcnVaultTicketStruct.serialize({
    instructionDiscriminator: initializeNcnVaultTicketInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.ncn,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.ncnVaultTicket,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.admin,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
