/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category InitializeNcnOperatorState
 * @category generated
 */
export const InitializeNcnOperatorStateStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number
}>(
  [['instructionDiscriminator', beet.u8]],
  'InitializeNcnOperatorStateInstructionArgs'
)
/**
 * Accounts required by the _InitializeNcnOperatorState_ instruction
 *
 * @property [] config
 * @property [_writable_] ncn
 * @property [_writable_] operator
 * @property [_writable_] ncnOperatorState
 * @property [**signer**] admin
 * @property [_writable_, **signer**] payer
 * @category Instructions
 * @category InitializeNcnOperatorState
 * @category generated
 */
export type InitializeNcnOperatorStateInstructionAccounts = {
  config: web3.PublicKey
  ncn: web3.PublicKey
  operator: web3.PublicKey
  ncnOperatorState: web3.PublicKey
  admin: web3.PublicKey
  payer: web3.PublicKey
  systemProgram?: web3.PublicKey
}

export const initializeNcnOperatorStateInstructionDiscriminator = 6

/**
 * Creates a _InitializeNcnOperatorState_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category InitializeNcnOperatorState
 * @category generated
 */
export function createInitializeNcnOperatorStateInstruction(
  accounts: InitializeNcnOperatorStateInstructionAccounts,
  programId = new web3.PublicKey('RestkWeAVL8fRGgzhfeoqFhsqKRchg6aa1XrcH96z4Q')
) {
  const [data] = InitializeNcnOperatorStateStruct.serialize({
    instructionDiscriminator:
      initializeNcnOperatorStateInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.ncn,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.operator,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.ncnOperatorState,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.admin,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
