/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category NcnSetAdmin
 * @category generated
 */
export const NcnSetAdminStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number;
}>([["instructionDiscriminator", beet.u8]], "NcnSetAdminInstructionArgs");
/**
 * Accounts required by the _NcnSetAdmin_ instruction
 *
 * @property [_writable_] ncn
 * @property [**signer**] oldAdmin
 * @property [**signer**] newAdmin
 * @category Instructions
 * @category NcnSetAdmin
 * @category generated
 */
export type NcnSetAdminInstructionAccounts = {
  ncn: web3.PublicKey;
  oldAdmin: web3.PublicKey;
  newAdmin: web3.PublicKey;
};

export const ncnSetAdminInstructionDiscriminator = 17;

/**
 * Creates a _NcnSetAdmin_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category NcnSetAdmin
 * @category generated
 */
export function createNcnSetAdminInstruction(
  accounts: NcnSetAdminInstructionAccounts,
  programId = new web3.PublicKey("RestkWeAVL8fRGgzhfeoqFhsqKRchg6aa1XrcH96z4Q"),
) {
  const [data] = NcnSetAdminStruct.serialize({
    instructionDiscriminator: ncnSetAdminInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.ncn,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.oldAdmin,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.newAdmin,
      isWritable: false,
      isSigner: true,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
