/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category OperatorDelegateTokenAccount
 * @category generated
 */
export const OperatorDelegateTokenAccountStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number
}>(
  [['instructionDiscriminator', beet.u8]],
  'OperatorDelegateTokenAccountInstructionArgs'
)
/**
 * Accounts required by the _OperatorDelegateTokenAccount_ instruction
 *
 * @property [] operator
 * @property [**signer**] delegateAdmin
 * @property [] tokenMint
 * @property [_writable_] tokenAccount
 * @property [] delegate
 * @category Instructions
 * @category OperatorDelegateTokenAccount
 * @category generated
 */
export type OperatorDelegateTokenAccountInstructionAccounts = {
  operator: web3.PublicKey
  delegateAdmin: web3.PublicKey
  tokenMint: web3.PublicKey
  tokenAccount: web3.PublicKey
  delegate: web3.PublicKey
  tokenProgram?: web3.PublicKey
}

export const operatorDelegateTokenAccountInstructionDiscriminator = 23

/**
 * Creates a _OperatorDelegateTokenAccount_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category OperatorDelegateTokenAccount
 * @category generated
 */
export function createOperatorDelegateTokenAccountInstruction(
  accounts: OperatorDelegateTokenAccountInstructionAccounts,
  programId = new web3.PublicKey('RestkWeAVL8fRGgzhfeoqFhsqKRchg6aa1XrcH96z4Q')
) {
  const [data] = OperatorDelegateTokenAccountStruct.serialize({
    instructionDiscriminator:
      operatorDelegateTokenAccountInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.operator,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.delegateAdmin,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.tokenMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.delegate,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
