/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category OperatorSetAdmin
 * @category generated
 */
export const OperatorSetAdminStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number
}>([['instructionDiscriminator', beet.u8]], 'OperatorSetAdminInstructionArgs')
/**
 * Accounts required by the _OperatorSetAdmin_ instruction
 *
 * @property [_writable_] operator
 * @property [**signer**] oldAdmin
 * @property [**signer**] newAdmin
 * @category Instructions
 * @category OperatorSetAdmin
 * @category generated
 */
export type OperatorSetAdminInstructionAccounts = {
  operator: web3.PublicKey
  oldAdmin: web3.PublicKey
  newAdmin: web3.PublicKey
}

export const operatorSetAdminInstructionDiscriminator = 19

/**
 * Creates a _OperatorSetAdmin_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category OperatorSetAdmin
 * @category generated
 */
export function createOperatorSetAdminInstruction(
  accounts: OperatorSetAdminInstructionAccounts,
  programId = new web3.PublicKey('RestkWeAVL8fRGgzhfeoqFhsqKRchg6aa1XrcH96z4Q')
) {
  const [data] = OperatorSetAdminStruct.serialize({
    instructionDiscriminator: operatorSetAdminInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.operator,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.oldAdmin,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.newAdmin,
      isWritable: false,
      isSigner: true,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
