/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category OperatorSetFee
 * @category generated
 */
export type OperatorSetFeeInstructionArgs = {
  newFeeBps: number
}
/**
 * @category Instructions
 * @category OperatorSetFee
 * @category generated
 */
export const OperatorSetFeeStruct = new beet.BeetArgsStruct<
  OperatorSetFeeInstructionArgs & {
    instructionDiscriminator: number
  }
>(
  [
    ['instructionDiscriminator', beet.u8],
    ['newFeeBps', beet.u16],
  ],
  'OperatorSetFeeInstructionArgs'
)
/**
 * Accounts required by the _OperatorSetFee_ instruction
 *
 * @property [] config
 * @property [_writable_] operator
 * @property [**signer**] admin
 * @category Instructions
 * @category OperatorSetFee
 * @category generated
 */
export type OperatorSetFeeInstructionAccounts = {
  config: web3.PublicKey
  operator: web3.PublicKey
  admin: web3.PublicKey
}

export const operatorSetFeeInstructionDiscriminator = 21

/**
 * Creates a _OperatorSetFee_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category OperatorSetFee
 * @category generated
 */
export function createOperatorSetFeeInstruction(
  accounts: OperatorSetFeeInstructionAccounts,
  args: OperatorSetFeeInstructionArgs,
  programId = new web3.PublicKey('RestkWeAVL8fRGgzhfeoqFhsqKRchg6aa1XrcH96z4Q')
) {
  const [data] = OperatorSetFeeStruct.serialize({
    instructionDiscriminator: operatorSetFeeInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.operator,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.admin,
      isWritable: false,
      isSigner: true,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
