/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link Config}
 * @category Accounts
 * @category generated
 */
export type ConfigArgs = {
  admin: web3.PublicKey
  restakingProgram: web3.PublicKey
  epochLength: beet.bignum
  numVaults: beet.bignum
  depositWithdrawalFeeCapBps: number
  feeRateOfChangeBps: number
  feeBumpBps: number
  programFeeBps: number
  programFeeWallet: web3.PublicKey
  feeAdmin: web3.PublicKey
  bump: number
  reserved: number[] /* size: 229 */
}
/**
 * Holds the data for the {@link Config} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class Config implements ConfigArgs {
  private constructor(
    readonly admin: web3.PublicKey,
    readonly restakingProgram: web3.PublicKey,
    readonly epochLength: beet.bignum,
    readonly numVaults: beet.bignum,
    readonly depositWithdrawalFeeCapBps: number,
    readonly feeRateOfChangeBps: number,
    readonly feeBumpBps: number,
    readonly programFeeBps: number,
    readonly programFeeWallet: web3.PublicKey,
    readonly feeAdmin: web3.PublicKey,
    readonly bump: number,
    readonly reserved: number[] /* size: 229 */
  ) {}

  /**
   * Creates a {@link Config} instance from the provided args.
   */
  static fromArgs(args: ConfigArgs) {
    return new Config(
      args.admin,
      args.restakingProgram,
      args.epochLength,
      args.numVaults,
      args.depositWithdrawalFeeCapBps,
      args.feeRateOfChangeBps,
      args.feeBumpBps,
      args.programFeeBps,
      args.programFeeWallet,
      args.feeAdmin,
      args.bump,
      args.reserved
    )
  }

  /**
   * Deserializes the {@link Config} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [Config, number] {
    return Config.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Config} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<Config> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find Config account at ${address}`)
    }
    return Config.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, configBeet)
  }

  /**
   * Deserializes the {@link Config} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [Config, number] {
    return configBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link Config} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return configBeet.serialize(this)
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link Config}
   */
  static get byteSize() {
    return configBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link Config} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      Config.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link Config} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === Config.byteSize
  }

  /**
   * Returns a readable version of {@link Config} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      admin: this.admin.toBase58(),
      restakingProgram: this.restakingProgram.toBase58(),
      epochLength: (() => {
        const x = <{ toNumber: () => number }>this.epochLength
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      numVaults: (() => {
        const x = <{ toNumber: () => number }>this.numVaults
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      depositWithdrawalFeeCapBps: this.depositWithdrawalFeeCapBps,
      feeRateOfChangeBps: this.feeRateOfChangeBps,
      feeBumpBps: this.feeBumpBps,
      programFeeBps: this.programFeeBps,
      programFeeWallet: this.programFeeWallet.toBase58(),
      feeAdmin: this.feeAdmin.toBase58(),
      bump: this.bump,
      reserved: this.reserved,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const configBeet = new beet.BeetStruct<Config, ConfigArgs>(
  [
    ['admin', beetSolana.publicKey],
    ['restakingProgram', beetSolana.publicKey],
    ['epochLength', beet.u64],
    ['numVaults', beet.u64],
    ['depositWithdrawalFeeCapBps', beet.u16],
    ['feeRateOfChangeBps', beet.u16],
    ['feeBumpBps', beet.u16],
    ['programFeeBps', beet.u16],
    ['programFeeWallet', beetSolana.publicKey],
    ['feeAdmin', beetSolana.publicKey],
    ['bump', beet.u8],
    ['reserved', beet.uniformFixedSizeArray(beet.u8, 229)],
  ],
  Config.fromArgs,
  'Config'
)
