/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link VaultStakerWithdrawalTicket}
 * @category Accounts
 * @category generated
 */
export type VaultStakerWithdrawalTicketArgs = {
  vault: web3.PublicKey
  staker: web3.PublicKey
  base: web3.PublicKey
  vrtAmount: beet.bignum
  slotUnstaked: beet.bignum
  bump: number
  reserved: number[] /* size: 263 */
}
/**
 * Holds the data for the {@link VaultStakerWithdrawalTicket} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class VaultStakerWithdrawalTicket
  implements VaultStakerWithdrawalTicketArgs
{
  private constructor(
    readonly vault: web3.PublicKey,
    readonly staker: web3.PublicKey,
    readonly base: web3.PublicKey,
    readonly vrtAmount: beet.bignum,
    readonly slotUnstaked: beet.bignum,
    readonly bump: number,
    readonly reserved: number[] /* size: 263 */
  ) {}

  /**
   * Creates a {@link VaultStakerWithdrawalTicket} instance from the provided args.
   */
  static fromArgs(args: VaultStakerWithdrawalTicketArgs) {
    return new VaultStakerWithdrawalTicket(
      args.vault,
      args.staker,
      args.base,
      args.vrtAmount,
      args.slotUnstaked,
      args.bump,
      args.reserved
    )
  }

  /**
   * Deserializes the {@link VaultStakerWithdrawalTicket} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [VaultStakerWithdrawalTicket, number] {
    return VaultStakerWithdrawalTicket.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link VaultStakerWithdrawalTicket} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<VaultStakerWithdrawalTicket> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(
        `Unable to find VaultStakerWithdrawalTicket account at ${address}`
      )
    }
    return VaultStakerWithdrawalTicket.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(
      programId,
      vaultStakerWithdrawalTicketBeet
    )
  }

  /**
   * Deserializes the {@link VaultStakerWithdrawalTicket} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(
    buf: Buffer,
    offset = 0
  ): [VaultStakerWithdrawalTicket, number] {
    return vaultStakerWithdrawalTicketBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link VaultStakerWithdrawalTicket} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return vaultStakerWithdrawalTicketBeet.serialize(this)
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link VaultStakerWithdrawalTicket}
   */
  static get byteSize() {
    return vaultStakerWithdrawalTicketBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link VaultStakerWithdrawalTicket} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      VaultStakerWithdrawalTicket.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link VaultStakerWithdrawalTicket} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === VaultStakerWithdrawalTicket.byteSize
  }

  /**
   * Returns a readable version of {@link VaultStakerWithdrawalTicket} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      vault: this.vault.toBase58(),
      staker: this.staker.toBase58(),
      base: this.base.toBase58(),
      vrtAmount: (() => {
        const x = <{ toNumber: () => number }>this.vrtAmount
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      slotUnstaked: (() => {
        const x = <{ toNumber: () => number }>this.slotUnstaked
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      bump: this.bump,
      reserved: this.reserved,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const vaultStakerWithdrawalTicketBeet = new beet.BeetStruct<
  VaultStakerWithdrawalTicket,
  VaultStakerWithdrawalTicketArgs
>(
  [
    ['vault', beetSolana.publicKey],
    ['staker', beetSolana.publicKey],
    ['base', beetSolana.publicKey],
    ['vrtAmount', beet.u64],
    ['slotUnstaked', beet.u64],
    ['bump', beet.u8],
    ['reserved', beet.uniformFixedSizeArray(beet.u8, 263)],
  ],
  VaultStakerWithdrawalTicket.fromArgs,
  'VaultStakerWithdrawalTicket'
)
