/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from "@solana/web3.js";
import * as beet from "@metaplex-foundation/beet";
import * as beetSolana from "@metaplex-foundation/beet-solana";

/**
 * Arguments used to create {@link VaultNcnSlasherOperatorTicket}
 * @category Accounts
 * @category generated
 */
export type VaultNcnSlasherOperatorTicketArgs = {
  vault: web3.PublicKey;
  ncn: web3.PublicKey;
  slasher: web3.PublicKey;
  operator: web3.PublicKey;
  epoch: beet.bignum;
  slashed: beet.bignum;
  bump: number;
  reserved: number[] /* size: 263 */;
};
/**
 * Holds the data for the {@link VaultNcnSlasherOperatorTicket} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class VaultNcnSlasherOperatorTicket
  implements VaultNcnSlasherOperatorTicketArgs
{
  private constructor(
    readonly vault: web3.PublicKey,
    readonly ncn: web3.PublicKey,
    readonly slasher: web3.PublicKey,
    readonly operator: web3.PublicKey,
    readonly epoch: beet.bignum,
    readonly slashed: beet.bignum,
    readonly bump: number,
    readonly reserved: number[] /* size: 263 */,
  ) {}

  /**
   * Creates a {@link VaultNcnSlasherOperatorTicket} instance from the provided args.
   */
  static fromArgs(args: VaultNcnSlasherOperatorTicketArgs) {
    return new VaultNcnSlasherOperatorTicket(
      args.vault,
      args.ncn,
      args.slasher,
      args.operator,
      args.epoch,
      args.slashed,
      args.bump,
      args.reserved,
    );
  }

  /**
   * Deserializes the {@link VaultNcnSlasherOperatorTicket} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [VaultNcnSlasherOperatorTicket, number] {
    return VaultNcnSlasherOperatorTicket.deserialize(accountInfo.data, offset);
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link VaultNcnSlasherOperatorTicket} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<VaultNcnSlasherOperatorTicket> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    );
    if (accountInfo == null) {
      throw new Error(
        `Unable to find VaultNcnSlasherOperatorTicket account at ${address}`,
      );
    }
    return VaultNcnSlasherOperatorTicket.fromAccountInfo(accountInfo, 0)[0];
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      "Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8",
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(
      programId,
      vaultNcnSlasherOperatorTicketBeet,
    );
  }

  /**
   * Deserializes the {@link VaultNcnSlasherOperatorTicket} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(
    buf: Buffer,
    offset = 0,
  ): [VaultNcnSlasherOperatorTicket, number] {
    return vaultNcnSlasherOperatorTicketBeet.deserialize(buf, offset);
  }

  /**
   * Serializes the {@link VaultNcnSlasherOperatorTicket} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return vaultNcnSlasherOperatorTicketBeet.serialize(this);
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link VaultNcnSlasherOperatorTicket}
   */
  static get byteSize() {
    return vaultNcnSlasherOperatorTicketBeet.byteSize;
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link VaultNcnSlasherOperatorTicket} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      VaultNcnSlasherOperatorTicket.byteSize,
      commitment,
    );
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link VaultNcnSlasherOperatorTicket} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === VaultNcnSlasherOperatorTicket.byteSize;
  }

  /**
   * Returns a readable version of {@link VaultNcnSlasherOperatorTicket} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      vault: this.vault.toBase58(),
      ncn: this.ncn.toBase58(),
      slasher: this.slasher.toBase58(),
      operator: this.operator.toBase58(),
      epoch: (() => {
        const x = <{ toNumber: () => number }>this.epoch;
        if (typeof x.toNumber === "function") {
          try {
            return x.toNumber();
          } catch (_) {
            return x;
          }
        }
        return x;
      })(),
      slashed: (() => {
        const x = <{ toNumber: () => number }>this.slashed;
        if (typeof x.toNumber === "function") {
          try {
            return x.toNumber();
          } catch (_) {
            return x;
          }
        }
        return x;
      })(),
      bump: this.bump,
      reserved: this.reserved,
    };
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const vaultNcnSlasherOperatorTicketBeet = new beet.BeetStruct<
  VaultNcnSlasherOperatorTicket,
  VaultNcnSlasherOperatorTicketArgs
>(
  [
    ["vault", beetSolana.publicKey],
    ["ncn", beetSolana.publicKey],
    ["slasher", beetSolana.publicKey],
    ["operator", beetSolana.publicKey],
    ["epoch", beet.u64],
    ["slashed", beet.u64],
    ["bump", beet.u8],
    ["reserved", beet.uniformFixedSizeArray(beet.u8, 263)],
  ],
  VaultNcnSlasherOperatorTicket.fromArgs,
  "VaultNcnSlasherOperatorTicket",
);
