import "./globals.css";

import type { Metadata } from "next";
import Link from "next/link";
import Header from "@/components/Header";
import { ClusterProvider } from "@/components/cluster/cluster-data-access";
import { SolanaProvider } from "@/components/solana/solana-provider";
import { ReactQueryProvider } from "./react-query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menuItems = [
    {
      title: "Vault",
      subItems: [
        {
          title: "Overview",
          href: "/vaults",
        },
        {
          title: "Initialize Vault",
          href: "/initialize-vault",
        },
        {
          title: "Mint",
          href: "/mint-to",
        },
      ],
    },
    {
      title: "Operator",
      subItems: [
        {
          title: "Initialize Operator",
          href: "/operator/initialize",
        },
        {
          title: "Initialize Operator Vault Ticket",
          href: "/operator/initialize-operator-vault-ticket",
        },
      ],
    },
    {
      title: "NCN",
      subItems: [
        {
          title: "Initialize NCN",
          href: "/ncn/initialize",
        },
      ],
    },
  ];

  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <div className="bg-black text-white min-h-screen flex">
                {/* Sidebar */}
                <aside className="w-64 min-h-screen p-6 border-r border-gray-700">
                  <Link href="/" className="text-xl font-bold mb-4">
                    Jito Restaking Dashboard
                  </Link>
                  <nav className="my-6">
                    <ul className="space-y-3">
                      {menuItems.map((menu) => (
                        <li key={menu.title}>
                          <div className="flex items-center justify-between cursor-pointer text-gray-400 hover:text-white">
                            <span>{menu.title}</span>
                            {/* {openMenus[menu.title] ? (
                              <ChevronDown size={16} />
                            ) : (
                              <ChevronRight size={16} />
                            )} */}
                          </div>
                          <ul className="pl-4 mt-2 space-y-2">
                              {menu.subItems.map((subItem) => (
                                <li key={subItem.title}>
                                  <Link
                                    href={subItem.href}
                                    className="block text-gray-500 hover:text-white"
                                  >
                                    {subItem.title}
                                  </Link>
                                </li>
                              ))}
                            </ul>
                        </li>
                      ))}
                    </ul>
                  </nav>
                </aside>

                <div className="flex-1">
                  <Header />

                  {/* Page Content */}
                  <div className="p-6">{children}</div>
                </div>
              </div>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
