/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category AddDelegation
 * @category generated
 */
export type AddDelegationInstructionArgs = {
  amount: beet.bignum;
};
/**
 * @category Instructions
 * @category AddDelegation
 * @category generated
 */
export const AddDelegationStruct = new beet.BeetArgsStruct<
  AddDelegationInstructionArgs & {
    instructionDiscriminator: number;
  }
>(
  [
    ["instructionDiscriminator", beet.u8],
    ["amount", beet.u64],
  ],
  "AddDelegationInstructionArgs",
);
/**
 * Accounts required by the _AddDelegation_ instruction
 *
 * @property [] config
 * @property [_writable_] vault
 * @property [] operator
 * @property [_writable_] vaultOperatorDelegation
 * @property [**signer**] admin
 * @category Instructions
 * @category AddDelegation
 * @category generated
 */
export type AddDelegationInstructionAccounts = {
  config: web3.PublicKey;
  vault: web3.PublicKey;
  operator: web3.PublicKey;
  vaultOperatorDelegation: web3.PublicKey;
  admin: web3.PublicKey;
};

export const addDelegationInstructionDiscriminator = 23;

/**
 * Creates a _AddDelegation_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category AddDelegation
 * @category generated
 */
export function createAddDelegationInstruction(
  accounts: AddDelegationInstructionAccounts,
  args: AddDelegationInstructionArgs,
  programId = new web3.PublicKey("Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"),
) {
  const [data] = AddDelegationStruct.serialize({
    instructionDiscriminator: addDelegationInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.operator,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultOperatorDelegation,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.admin,
      isWritable: false,
      isSigner: true,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
