/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category ChangeWithdrawalTicketOwner
 * @category generated
 */
export const ChangeWithdrawalTicketOwnerStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number;
}>(
  [["instructionDiscriminator", beet.u8]],
  "ChangeWithdrawalTicketOwnerInstructionArgs",
);
/**
 * Accounts required by the _ChangeWithdrawalTicketOwner_ instruction
 *
 * @property [] config
 * @property [] vault
 * @property [_writable_] vaultStakerWithdrawalTicket
 * @property [**signer**] oldOwner
 * @property [] newOwner
 * @category Instructions
 * @category ChangeWithdrawalTicketOwner
 * @category generated
 */
export type ChangeWithdrawalTicketOwnerInstructionAccounts = {
  config: web3.PublicKey;
  vault: web3.PublicKey;
  vaultStakerWithdrawalTicket: web3.PublicKey;
  oldOwner: web3.PublicKey;
  newOwner: web3.PublicKey;
};

export const changeWithdrawalTicketOwnerInstructionDiscriminator = 13;

/**
 * Creates a _ChangeWithdrawalTicketOwner_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category ChangeWithdrawalTicketOwner
 * @category generated
 */
export function createChangeWithdrawalTicketOwnerInstruction(
  accounts: ChangeWithdrawalTicketOwnerInstructionAccounts,
  programId = new web3.PublicKey("Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"),
) {
  const [data] = ChangeWithdrawalTicketOwnerStruct.serialize({
    instructionDiscriminator:
      changeWithdrawalTicketOwnerInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultStakerWithdrawalTicket,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.oldOwner,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.newOwner,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
