/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category CooldownVaultNcnTicket
 * @category generated
 */
export const CooldownVaultNcnTicketStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number;
}>(
  [["instructionDiscriminator", beet.u8]],
  "CooldownVaultNcnTicketInstructionArgs",
);
/**
 * Accounts required by the _CooldownVaultNcnTicket_ instruction
 *
 * @property [] config
 * @property [] vault
 * @property [] ncn
 * @property [_writable_] vaultNcnTicket
 * @property [**signer**] admin
 * @category Instructions
 * @category CooldownVaultNcnTicket
 * @category generated
 */
export type CooldownVaultNcnTicketInstructionAccounts = {
  config: web3.PublicKey;
  vault: web3.PublicKey;
  ncn: web3.PublicKey;
  vaultNcnTicket: web3.PublicKey;
  admin: web3.PublicKey;
};

export const cooldownVaultNcnTicketInstructionDiscriminator = 8;

/**
 * Creates a _CooldownVaultNcnTicket_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category CooldownVaultNcnTicket
 * @category generated
 */
export function createCooldownVaultNcnTicketInstruction(
  accounts: CooldownVaultNcnTicketInstructionAccounts,
  programId = new web3.PublicKey("Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"),
) {
  const [data] = CooldownVaultNcnTicketStruct.serialize({
    instructionDiscriminator: cooldownVaultNcnTicketInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.ncn,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultNcnTicket,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.admin,
      isWritable: false,
      isSigner: true,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
