/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category CooldownVaultNcnSlasherTicket
 * @category generated
 */
export const CooldownVaultNcnSlasherTicketStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number;
}>(
  [["instructionDiscriminator", beet.u8]],
  "CooldownVaultNcnSlasherTicketInstructionArgs",
);
/**
 * Accounts required by the _CooldownVaultNcnSlasherTicket_ instruction
 *
 * @property [] config
 * @property [] vault
 * @property [] ncn
 * @property [] slasher
 * @property [_writable_] vaultNcnSlasherTicket
 * @property [**signer**] admin
 * @category Instructions
 * @category CooldownVaultNcnSlasherTicket
 * @category generated
 */
export type CooldownVaultNcnSlasherTicketInstructionAccounts = {
  config: web3.PublicKey;
  vault: web3.PublicKey;
  ncn: web3.PublicKey;
  slasher: web3.PublicKey;
  vaultNcnSlasherTicket: web3.PublicKey;
  admin: web3.PublicKey;
};

export const cooldownVaultNcnSlasherTicketInstructionDiscriminator = 10;

/**
 * Creates a _CooldownVaultNcnSlasherTicket_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category CooldownVaultNcnSlasherTicket
 * @category generated
 */
export function createCooldownVaultNcnSlasherTicketInstruction(
  accounts: CooldownVaultNcnSlasherTicketInstructionAccounts,
  programId = new web3.PublicKey("Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"),
) {
  const [data] = CooldownVaultNcnSlasherTicketStruct.serialize({
    instructionDiscriminator:
      cooldownVaultNcnSlasherTicketInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.ncn,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.slasher,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultNcnSlasherTicket,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.admin,
      isWritable: false,
      isSigner: true,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
