/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category CrankVaultUpdateStateTracker
 * @category generated
 */
export const CrankVaultUpdateStateTrackerStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number;
}>(
  [["instructionDiscriminator", beet.u8]],
  "CrankVaultUpdateStateTrackerInstructionArgs",
);
/**
 * Accounts required by the _CrankVaultUpdateStateTracker_ instruction
 *
 * @property [] config
 * @property [_writable_] vault
 * @property [] operator
 * @property [_writable_] vaultOperatorDelegation
 * @property [_writable_] vaultUpdateStateTracker
 * @category Instructions
 * @category CrankVaultUpdateStateTracker
 * @category generated
 */
export type CrankVaultUpdateStateTrackerInstructionAccounts = {
  config: web3.PublicKey;
  vault: web3.PublicKey;
  operator: web3.PublicKey;
  vaultOperatorDelegation: web3.PublicKey;
  vaultUpdateStateTracker: web3.PublicKey;
};

export const crankVaultUpdateStateTrackerInstructionDiscriminator = 27;

/**
 * Creates a _CrankVaultUpdateStateTracker_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category CrankVaultUpdateStateTracker
 * @category generated
 */
export function createCrankVaultUpdateStateTrackerInstruction(
  accounts: CrankVaultUpdateStateTrackerInstructionAccounts,
  programId = new web3.PublicKey("Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"),
) {
  const [data] = CrankVaultUpdateStateTrackerStruct.serialize({
    instructionDiscriminator:
      crankVaultUpdateStateTrackerInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.operator,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultOperatorDelegation,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultUpdateStateTracker,
      isWritable: true,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
