/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from "@solana/spl-token";
import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category DelegateTokenAccount
 * @category generated
 */
export const DelegateTokenAccountStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number;
}>(
  [["instructionDiscriminator", beet.u8]],
  "DelegateTokenAccountInstructionArgs",
);
/**
 * Accounts required by the _DelegateTokenAccount_ instruction
 *
 * @property [] config
 * @property [] vault
 * @property [**signer**] delegateAssetAdmin
 * @property [] tokenMint
 * @property [_writable_] tokenAccount
 * @property [] delegate
 * @category Instructions
 * @category DelegateTokenAccount
 * @category generated
 */
export type DelegateTokenAccountInstructionAccounts = {
  config: web3.PublicKey;
  vault: web3.PublicKey;
  delegateAssetAdmin: web3.PublicKey;
  tokenMint: web3.PublicKey;
  tokenAccount: web3.PublicKey;
  delegate: web3.PublicKey;
  tokenProgram?: web3.PublicKey;
};

export const delegateTokenAccountInstructionDiscriminator = 20;

/**
 * Creates a _DelegateTokenAccount_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category DelegateTokenAccount
 * @category generated
 */
export function createDelegateTokenAccountInstruction(
  accounts: DelegateTokenAccountInstructionAccounts,
  programId = new web3.PublicKey("Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"),
) {
  const [data] = DelegateTokenAccountStruct.serialize({
    instructionDiscriminator: delegateTokenAccountInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.delegateAssetAdmin,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.tokenMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.delegate,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
