/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from "@solana/spl-token";
import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category EnqueueWithdrawal
 * @category generated
 */
export type EnqueueWithdrawalInstructionArgs = {
  amount: beet.bignum;
};
/**
 * @category Instructions
 * @category EnqueueWithdrawal
 * @category generated
 */
export const EnqueueWithdrawalStruct = new beet.BeetArgsStruct<
  EnqueueWithdrawalInstructionArgs & {
    instructionDiscriminator: number;
  }
>(
  [
    ["instructionDiscriminator", beet.u8],
    ["amount", beet.u64],
  ],
  "EnqueueWithdrawalInstructionArgs",
);
/**
 * Accounts required by the _EnqueueWithdrawal_ instruction
 *
 * @property [] config
 * @property [_writable_] vault
 * @property [_writable_] vaultStakerWithdrawalTicket
 * @property [_writable_] vaultStakerWithdrawalTicketTokenAccount
 * @property [_writable_, **signer**] staker
 * @property [_writable_] stakerVrtTokenAccount
 * @property [**signer**] base
 * @property [**signer**] burnSigner (optional)
 * @category Instructions
 * @category EnqueueWithdrawal
 * @category generated
 */
export type EnqueueWithdrawalInstructionAccounts = {
  config: web3.PublicKey;
  vault: web3.PublicKey;
  vaultStakerWithdrawalTicket: web3.PublicKey;
  vaultStakerWithdrawalTicketTokenAccount: web3.PublicKey;
  staker: web3.PublicKey;
  stakerVrtTokenAccount: web3.PublicKey;
  base: web3.PublicKey;
  tokenProgram?: web3.PublicKey;
  systemProgram?: web3.PublicKey;
  burnSigner?: web3.PublicKey;
};

export const enqueueWithdrawalInstructionDiscriminator = 12;

/**
 * Creates a _EnqueueWithdrawal_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category EnqueueWithdrawal
 * @category generated
 */
export function createEnqueueWithdrawalInstruction(
  accounts: EnqueueWithdrawalInstructionAccounts,
  args: EnqueueWithdrawalInstructionArgs,
  programId = new web3.PublicKey("Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"),
) {
  const [data] = EnqueueWithdrawalStruct.serialize({
    instructionDiscriminator: enqueueWithdrawalInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultStakerWithdrawalTicket,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultStakerWithdrawalTicketTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.staker,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.stakerVrtTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.base,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.burnSigner ?? programId,
      isWritable: false,
      isSigner: accounts.burnSigner != null,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
