/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category InitializeVaultOperatorDelegation
 * @category generated
 */
export const InitializeVaultOperatorDelegationStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number;
}>(
  [["instructionDiscriminator", beet.u8]],
  "InitializeVaultOperatorDelegationInstructionArgs",
);
/**
 * Accounts required by the _InitializeVaultOperatorDelegation_ instruction
 *
 * @property [] config
 * @property [_writable_] vault
 * @property [_writable_] operator
 * @property [] operatorVaultTicket
 * @property [_writable_] vaultOperatorDelegation
 * @property [**signer**] admin
 * @property [_writable_, **signer**] payer
 * @category Instructions
 * @category InitializeVaultOperatorDelegation
 * @category generated
 */
export type InitializeVaultOperatorDelegationInstructionAccounts = {
  config: web3.PublicKey;
  vault: web3.PublicKey;
  operator: web3.PublicKey;
  operatorVaultTicket: web3.PublicKey;
  vaultOperatorDelegation: web3.PublicKey;
  admin: web3.PublicKey;
  payer: web3.PublicKey;
  systemProgram?: web3.PublicKey;
};

export const initializeVaultOperatorDelegationInstructionDiscriminator = 3;

/**
 * Creates a _InitializeVaultOperatorDelegation_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category InitializeVaultOperatorDelegation
 * @category generated
 */
export function createInitializeVaultOperatorDelegationInstruction(
  accounts: InitializeVaultOperatorDelegationInstructionAccounts,
  programId = new web3.PublicKey("Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"),
) {
  const [data] = InitializeVaultOperatorDelegationStruct.serialize({
    instructionDiscriminator:
      initializeVaultOperatorDelegationInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.operator,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.operatorVaultTicket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultOperatorDelegation,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.admin,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
