/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category InitializeConfig
 * @category generated
 */
export type InitializeConfigInstructionArgs = {
  programFeeBps: number;
};
/**
 * @category Instructions
 * @category InitializeConfig
 * @category generated
 */
export const InitializeConfigStruct = new beet.BeetArgsStruct<
  InitializeConfigInstructionArgs & {
    instructionDiscriminator: number;
  }
>(
  [
    ["instructionDiscriminator", beet.u8],
    ["programFeeBps", beet.u16],
  ],
  "InitializeConfigInstructionArgs",
);
/**
 * Accounts required by the _InitializeConfig_ instruction
 *
 * @property [_writable_] config
 * @property [_writable_, **signer**] admin
 * @property [] restakingProgram
 * @property [] programFeeWallet
 * @category Instructions
 * @category InitializeConfig
 * @category generated
 */
export type InitializeConfigInstructionAccounts = {
  config: web3.PublicKey;
  admin: web3.PublicKey;
  restakingProgram: web3.PublicKey;
  programFeeWallet: web3.PublicKey;
  systemProgram?: web3.PublicKey;
};

export const initializeConfigInstructionDiscriminator = 0;

/**
 * Creates a _InitializeConfig_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category InitializeConfig
 * @category generated
 */
export function createInitializeConfigInstruction(
  accounts: InitializeConfigInstructionAccounts,
  args: InitializeConfigInstructionArgs,
  programId = new web3.PublicKey("Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"),
) {
  const [data] = InitializeConfigStruct.serialize({
    instructionDiscriminator: initializeConfigInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.admin,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.restakingProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.programFeeWallet,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
