/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category InitializeVaultNcnSlasherTicket
 * @category generated
 */
export const InitializeVaultNcnSlasherTicketStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number;
}>(
  [["instructionDiscriminator", beet.u8]],
  "InitializeVaultNcnSlasherTicketInstructionArgs",
);
/**
 * Accounts required by the _InitializeVaultNcnSlasherTicket_ instruction
 *
 * @property [] config
 * @property [] vault
 * @property [] ncn
 * @property [] slasher
 * @property [] ncnSlasherTicket
 * @property [_writable_] vaultSlasherTicket
 * @property [**signer**] admin
 * @property [_writable_, **signer**] payer
 * @category Instructions
 * @category InitializeVaultNcnSlasherTicket
 * @category generated
 */
export type InitializeVaultNcnSlasherTicketInstructionAccounts = {
  config: web3.PublicKey;
  vault: web3.PublicKey;
  ncn: web3.PublicKey;
  slasher: web3.PublicKey;
  ncnSlasherTicket: web3.PublicKey;
  vaultSlasherTicket: web3.PublicKey;
  admin: web3.PublicKey;
  payer: web3.PublicKey;
  systemProgram?: web3.PublicKey;
};

export const initializeVaultNcnSlasherTicketInstructionDiscriminator = 6;

/**
 * Creates a _InitializeVaultNcnSlasherTicket_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category InitializeVaultNcnSlasherTicket
 * @category generated
 */
export function createInitializeVaultNcnSlasherTicketInstruction(
  accounts: InitializeVaultNcnSlasherTicketInstructionAccounts,
  programId = new web3.PublicKey("Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"),
) {
  const [data] = InitializeVaultNcnSlasherTicketStruct.serialize({
    instructionDiscriminator:
      initializeVaultNcnSlasherTicketInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.ncn,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.slasher,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.ncnSlasherTicket,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultSlasherTicket,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.admin,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
