/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category MintTo
 * @category generated
 */
export type MintToInstructionArgs = {
  amountIn: beet.bignum
  minAmountOut: beet.bignum
}
/**
 * @category Instructions
 * @category MintTo
 * @category generated
 */
export const MintToStruct = new beet.BeetArgsStruct<
  MintToInstructionArgs & {
    instructionDiscriminator: number
  }
>(
  [
    ['instructionDiscriminator', beet.u8],
    ['amountIn', beet.u64],
    ['minAmountOut', beet.u64],
  ],
  'MintToInstructionArgs'
)
/**
 * Accounts required by the _MintTo_ instruction
 *
 * @property [] config
 * @property [_writable_] vault
 * @property [_writable_] vrtMint
 * @property [_writable_, **signer**] depositor
 * @property [_writable_] depositorTokenAccount
 * @property [_writable_] vaultTokenAccount
 * @property [_writable_] depositorVrtTokenAccount
 * @property [_writable_] vaultFeeTokenAccount
 * @property [**signer**] mintSigner (optional)
 * @category Instructions
 * @category MintTo
 * @category generated
 */
export type MintToInstructionAccounts = {
  config: web3.PublicKey
  vault: web3.PublicKey
  vrtMint: web3.PublicKey
  depositor: web3.PublicKey
  depositorTokenAccount: web3.PublicKey
  vaultTokenAccount: web3.PublicKey
  depositorVrtTokenAccount: web3.PublicKey
  vaultFeeTokenAccount: web3.PublicKey
  tokenProgram?: web3.PublicKey
  mintSigner?: web3.PublicKey
}

export const mintToInstructionDiscriminator = 11

/**
 * Creates a _MintTo_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category MintTo
 * @category generated
 */
export function createMintToInstruction(
  accounts: MintToInstructionAccounts,
  args: MintToInstructionArgs,
  programId = new web3.PublicKey('Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8')
) {
  const [data] = MintToStruct.serialize({
    instructionDiscriminator: mintToInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vrtMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.depositor,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.depositorTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.depositorVrtTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultFeeTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.mintSigner ?? programId,
      isWritable: false,
      isSigner: accounts.mintSigner != null,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
