/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category SetConfigAdmin
 * @category generated
 */
export const SetConfigAdminStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number;
}>([["instructionDiscriminator", beet.u8]], "SetConfigAdminInstructionArgs");
/**
 * Accounts required by the _SetConfigAdmin_ instruction
 *
 * @property [_writable_] config
 * @property [**signer**] oldAdmin
 * @property [] newAdmin
 * @category Instructions
 * @category SetConfigAdmin
 * @category generated
 */
export type SetConfigAdminInstructionAccounts = {
  config: web3.PublicKey;
  oldAdmin: web3.PublicKey;
  newAdmin: web3.PublicKey;
};

export const setConfigAdminInstructionDiscriminator = 31;

/**
 * Creates a _SetConfigAdmin_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category SetConfigAdmin
 * @category generated
 */
export function createSetConfigAdminInstruction(
  accounts: SetConfigAdminInstructionAccounts,
  programId = new web3.PublicKey("Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"),
) {
  const [data] = SetConfigAdminStruct.serialize({
    instructionDiscriminator: setConfigAdminInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.oldAdmin,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.newAdmin,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
