/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category SetDepositCapacity
 * @category generated
 */
export type SetDepositCapacityInstructionArgs = {
  amount: beet.bignum;
};
/**
 * @category Instructions
 * @category SetDepositCapacity
 * @category generated
 */
export const SetDepositCapacityStruct = new beet.BeetArgsStruct<
  SetDepositCapacityInstructionArgs & {
    instructionDiscriminator: number;
  }
>(
  [
    ["instructionDiscriminator", beet.u8],
    ["amount", beet.u64],
  ],
  "SetDepositCapacityInstructionArgs",
);
/**
 * Accounts required by the _SetDepositCapacity_ instruction
 *
 * @property [] config
 * @property [_writable_] vault
 * @property [**signer**] admin
 * @category Instructions
 * @category SetDepositCapacity
 * @category generated
 */
export type SetDepositCapacityInstructionAccounts = {
  config: web3.PublicKey;
  vault: web3.PublicKey;
  admin: web3.PublicKey;
};

export const setDepositCapacityInstructionDiscriminator = 15;

/**
 * Creates a _SetDepositCapacity_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category SetDepositCapacity
 * @category generated
 */
export function createSetDepositCapacityInstruction(
  accounts: SetDepositCapacityInstructionAccounts,
  args: SetDepositCapacityInstructionArgs,
  programId = new web3.PublicKey("Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"),
) {
  const [data] = SetDepositCapacityStruct.serialize({
    instructionDiscriminator: setDepositCapacityInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.admin,
      isWritable: false,
      isSigner: true,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
