/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category SetFees
 * @category generated
 */
export type SetFeesInstructionArgs = {
  depositFeeBps: beet.COption<number>;
  withdrawalFeeBps: beet.COption<number>;
  rewardFeeBps: beet.COption<number>;
};
/**
 * @category Instructions
 * @category SetFees
 * @category generated
 */
export const SetFeesStruct = new beet.FixableBeetArgsStruct<
  SetFeesInstructionArgs & {
    instructionDiscriminator: number;
  }
>(
  [
    ["instructionDiscriminator", beet.u8],
    ["depositFeeBps", beet.coption(beet.u16)],
    ["withdrawalFeeBps", beet.coption(beet.u16)],
    ["rewardFeeBps", beet.coption(beet.u16)],
  ],
  "SetFeesInstructionArgs",
);
/**
 * Accounts required by the _SetFees_ instruction
 *
 * @property [] config
 * @property [_writable_] vault
 * @property [**signer**] admin
 * @category Instructions
 * @category SetFees
 * @category generated
 */
export type SetFeesInstructionAccounts = {
  config: web3.PublicKey;
  vault: web3.PublicKey;
  admin: web3.PublicKey;
};

export const setFeesInstructionDiscriminator = 16;

/**
 * Creates a _SetFees_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category SetFees
 * @category generated
 */
export function createSetFeesInstruction(
  accounts: SetFeesInstructionAccounts,
  args: SetFeesInstructionArgs,
  programId = new web3.PublicKey("Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"),
) {
  const [data] = SetFeesStruct.serialize({
    instructionDiscriminator: setFeesInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.admin,
      isWritable: false,
      isSigner: true,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
