/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category SetIsPaused
 * @category generated
 */
export type SetIsPausedInstructionArgs = {
  isPaused: boolean;
};
/**
 * @category Instructions
 * @category SetIsPaused
 * @category generated
 */
export const SetIsPausedStruct = new beet.BeetArgsStruct<
  SetIsPausedInstructionArgs & {
    instructionDiscriminator: number;
  }
>(
  [
    ["instructionDiscriminator", beet.u8],
    ["isPaused", beet.bool],
  ],
  "SetIsPausedInstructionArgs",
);
/**
 * Accounts required by the _SetIsPaused_ instruction
 *
 * @property [] config
 * @property [_writable_] vault
 * @property [**signer**] admin
 * @category Instructions
 * @category SetIsPaused
 * @category generated
 */
export type SetIsPausedInstructionAccounts = {
  config: web3.PublicKey;
  vault: web3.PublicKey;
  admin: web3.PublicKey;
};

export const setIsPausedInstructionDiscriminator = 19;

/**
 * Creates a _SetIsPaused_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category SetIsPaused
 * @category generated
 */
export function createSetIsPausedInstruction(
  accounts: SetIsPausedInstructionAccounts,
  args: SetIsPausedInstructionArgs,
  programId = new web3.PublicKey("Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"),
) {
  const [data] = SetIsPausedStruct.serialize({
    instructionDiscriminator: setIsPausedInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.admin,
      isWritable: false,
      isSigner: true,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
