/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";
import { VaultAdminRole, vaultAdminRoleBeet } from "../types/VaultAdminRole";

/**
 * @category Instructions
 * @category SetSecondaryAdmin
 * @category generated
 */
export type SetSecondaryAdminInstructionArgs = {
  vaultAdminRole: VaultAdminRole;
};
/**
 * @category Instructions
 * @category SetSecondaryAdmin
 * @category generated
 */
export const SetSecondaryAdminStruct = new beet.BeetArgsStruct<
  SetSecondaryAdminInstructionArgs & {
    instructionDiscriminator: number;
  }
>(
  [
    ["instructionDiscriminator", beet.u8],
    ["vaultAdminRole", vaultAdminRoleBeet],
  ],
  "SetSecondaryAdminInstructionArgs",
);
/**
 * Accounts required by the _SetSecondaryAdmin_ instruction
 *
 * @property [] config
 * @property [_writable_] vault
 * @property [**signer**] admin
 * @property [] newAdmin
 * @category Instructions
 * @category SetSecondaryAdmin
 * @category generated
 */
export type SetSecondaryAdminInstructionAccounts = {
  config: web3.PublicKey;
  vault: web3.PublicKey;
  admin: web3.PublicKey;
  newAdmin: web3.PublicKey;
};

export const setSecondaryAdminInstructionDiscriminator = 22;

/**
 * Creates a _SetSecondaryAdmin_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category SetSecondaryAdmin
 * @category generated
 */
export function createSetSecondaryAdminInstruction(
  accounts: SetSecondaryAdminInstructionAccounts,
  args: SetSecondaryAdminInstructionArgs,
  programId = new web3.PublicKey("Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"),
) {
  const [data] = SetSecondaryAdminStruct.serialize({
    instructionDiscriminator: setSecondaryAdminInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.admin,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.newAdmin,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
