/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from "@solana/spl-token";
import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category UpdateVaultBalance
 * @category generated
 */
export const UpdateVaultBalanceStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number;
}>(
  [["instructionDiscriminator", beet.u8]],
  "UpdateVaultBalanceInstructionArgs",
);
/**
 * Accounts required by the _UpdateVaultBalance_ instruction
 *
 * @property [] config
 * @property [_writable_] vault
 * @property [] vaultTokenAccount
 * @property [_writable_] vrtMint
 * @property [_writable_] vaultFeeTokenAccount
 * @category Instructions
 * @category UpdateVaultBalance
 * @category generated
 */
export type UpdateVaultBalanceInstructionAccounts = {
  config: web3.PublicKey;
  vault: web3.PublicKey;
  vaultTokenAccount: web3.PublicKey;
  vrtMint: web3.PublicKey;
  vaultFeeTokenAccount: web3.PublicKey;
  tokenProgram?: web3.PublicKey;
};

export const updateVaultBalanceInstructionDiscriminator = 25;

/**
 * Creates a _UpdateVaultBalance_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category UpdateVaultBalance
 * @category generated
 */
export function createUpdateVaultBalanceInstruction(
  accounts: UpdateVaultBalanceInstructionAccounts,
  programId = new web3.PublicKey("Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"),
) {
  const [data] = UpdateVaultBalanceStruct.serialize({
    instructionDiscriminator: updateVaultBalanceInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultTokenAccount,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vrtMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultFeeTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
