/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category WarmupVaultNcnTicket
 * @category generated
 */
export const WarmupVaultNcnTicketStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number
}>(
  [['instructionDiscriminator', beet.u8]],
  'WarmupVaultNcnTicketInstructionArgs'
)
/**
 * Accounts required by the _WarmupVaultNcnTicket_ instruction
 *
 * @property [] config
 * @property [_writable_] vault
 * @property [] ncn
 * @property [_writable_] vaultNcnTicket
 * @property [**signer**] admin
 * @category Instructions
 * @category WarmupVaultNcnTicket
 * @category generated
 */
export type WarmupVaultNcnTicketInstructionAccounts = {
  config: web3.PublicKey
  vault: web3.PublicKey
  ncn: web3.PublicKey
  vaultNcnTicket: web3.PublicKey
  admin: web3.PublicKey
}

export const warmupVaultNcnTicketInstructionDiscriminator = 7

/**
 * Creates a _WarmupVaultNcnTicket_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category WarmupVaultNcnTicket
 * @category generated
 */
export function createWarmupVaultNcnTicketInstruction(
  accounts: WarmupVaultNcnTicketInstructionAccounts,
  programId = new web3.PublicKey('Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8')
) {
  const [data] = WarmupVaultNcnTicketStruct.serialize({
    instructionDiscriminator: warmupVaultNcnTicketInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.config,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.ncn,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultNcnTicket,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.admin,
      isWritable: false,
      isSigner: true,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
